name: CI # workflow名，会显示在action界面中

on: # 定义触发器
	workflow_dispatch: # 手动触发
	schedule: # 周期触发
	    - cron: '0 14 * * 5' # 利用cron实现时间,注意是UTC时间
	    
# 当有对main分支的push和pr提交时自动执行
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 允许手动执行
  workflow_dispatch:


# 单个workflow由一些jobs构成，这些jobs可以并行也可以串行
jobs: # 定义一些工作
  
  build: # 工作名字, 可以任意取
    runs-on: ubuntu-latest # 在哪跑
    steps: # 工作步骤
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # 用shell运行单个命令
      - name: Run a one-line script
        run: echo Hello, world! # 这里是关键部分,可以让gpt写,其实就是脚本

      # 运行多个命令
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
